### ISSUE TITLE
Download of mp3 file failed

### ISSUE THREAD

**Issue by georf** [brokkr/poca#104] opened 2017-11-23 10:28 UTC
I get an error while downloading a mp3 file. But I don't know why its failing. If I download this file directly, I can fetch it. Perhaps you can add a detailed error message in the log file or only in verbose mode or something like that?
```
poca --config $(pwd) -v -l 
DAS ARD RADIOFEATURE. 1 ➕
 ⇵ ard-radiofeature-pulverfass-baltikum.12844s.mp3   [50 Mb]
 ⚠ Download of http://mp3-download.ard.de/radio/radiofeature/ard-radiofeature-pulverfass-baltikum.12844s.mp3  failed
```

Feed URL: http://www.ard.de/static/radio/radiofeature/rss/podcast.xml

```
wget http://mp3-download.ard.de/radio/radiofeature/ard-radiofeature-pulverfass-baltikum.12844s.mp3
--2017-11-23 11:26:32--  http://mp3-download.ard.de/radio/radiofeature/ard-radiofeature-pulverfass-baltikum.12844s.mp3
Resolving mp3-download.ard.de (mp3-download.ard.de)... 88.134.181.106, 88.134.181.97
Connecting to mp3-download.ard.de (mp3-download.ard.de)|88.134.181.106|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 53171689 (51M) [audio/mpeg]
Saving to: ‘ard-radiofeature-pulverfass-baltikum.12844s.mp3’

ard-radiofeature-pulverfass-baltikum.12844s.mp3       100%[===========================================================================================================================>]  50.71M  3.85MB/s   in 14s    

2017-11-23 11:26:46 (3.68 MB/s) - ‘ard-radiofeature-pulverfass-baltikum.12844s.mp3’ saved [53171689/53171689]
```

**Comment by brokkr** [comment] 2017-11-23 14:04
The issue seems simple enough: the url in the feed is 'http://mp3-download.ard.de/radio/radiofeature/ard-radiofeature-pulverfass-baltikum.12844s.mp3 ' with a space at the end. I will have to test some more to figure out whether the problem is keeping the space or if something discards the space along the way.

As for more informative errors: It's a valid point and I could just pass on whatever error message is generated (in this case it would be "No connection adapters were found for 'http://mp3-download.ard.de/radio/radiofeature/ard-radiofeature-pulverfass-baltikum.12844s.mp3'")

Mostly though I doubt it would be useful. I recently caught an error in BBC's Newhour feed where a single file in the middle of the feed was marked '403 UK only'. Like why? Usually it will just be human errors and there's little anyone can do about it except as you did, download it yourself if allowed.

**Comment by brokkr** [comment] 2017-11-23 19:07
`requests` processes the url so that it becomes: `http://mp3-download.ard.de/radio/radiofeature/ard-radiofeature-pulverfass-baltikum.12844s.mp3%20` I would awfully like to clean that up but there's a lot of ways for people to write urls wrong and no way to guard against them all. Some kind of general url sanitizing would require 3rd party libs and I think four is too many already.

I'll have a look at the output and see if there's a good way to add more informative errors somewhere.

**Comment by brokkr** [comment] 2021-05-02 16:16
More informative errors is now #126 
The wontfix applies to fixing server side naming errors

**Closed by brokkr** 2021-05-02 16:16 UTC
Labels: wontfix
